---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## Education

### Tianjin Medical University, School of Public Health
   Bachelor of Medicine in Preventive Medicine, September 2020 - June 2025

### University of California, Berkeley
   Exchange Student, fall 2023
   

## PROFESSIONAL EXPERIENCE

### Tianjin Center for Disease Control and Prevention 

   a.Collected samples from 13 schools and 3 hospitals in the district to check the sterilization conditions.
  
   b.Summarized and reported the data collected and re-measured any abnormalities.
   
### Tianjin Baodi Hospital

   a.Participated in rotations in varied departments, including internal medicine, surgery, gynecology, pediatrics, and emergency medicine.
   
   b.Assisted the chief physician with inpatient exams, patient arterial blood gas monitoring and analysis, etc., and facilitated multiple surgical procedures.

## PROJECT
 
### Associations of one-carbon metabolism-related nutrients and gene polymorphisms with preterm birth, low birth weight, and macrosomia: A birth cohort study in northern China

Established a prospective birth cohort that included 1123 data sets of pregnant women and analyze on this cohort.
  
## SKILLS & INTERESTS

Piano (Level 10 Certificate & National Award), Video Production.